Post/urls.py
from django.conf.urls import url
from . import views

app_name = 'Post'
urlpatterns = [
    url(r'^$',views.all_post,name='all_post'),
    url(r'^(?P<id>\d+)$' , views.post ,name='post'),
    url(r'^create$',views.create_post,name='create_post'),
    url(r'^(?P<id>\d+)/edit$' , views.edit_post ,name='edit_post'),

]

blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Post.urls',namespace='blog')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Post/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.




class Post(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField(max_length=50)
    content=RichTextField()
    img=models.ImageField(upload_to='post_img/',default="post_img/default.jpg")
    created=models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    

Post/forms.py
from django import forms
from .models import Post
from ckeditor.widgets import CKEditorWidget


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Post
        fields = ['title','content','img']

Post/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Post
from .forms import PostForm
# Create your views here.

def all_post(request):
    all_posts= Post.objects.filter(active = True)
    context = {
        'all_posts':all_posts,
    }
    return render(request,'allposts.html',context)



def post(request , id):
    #post=Post.objects.get(id=id)
    post = get_object_or_404(Post,id=id)
    context= {
        'post' : post
    }
    return render(request , "post.html",context)

def create_post(request):
    if request.method=='POST':
        form=PostForm(request.POST)
        if form.is_valid():
            newform=form.save(commit=False)
            newform.user=request.user
            newform.save()
            return redirect('/')

    else:
        form = PostForm()
    
    context = {
        'form': form ,
    }

    return render(request,'create.html',context)

def edit_post(request,id):
    post = get_object_or_404(Post ,id=id )
    if request.method=='POST':
        form=PostForm(request.POST,instance=post)
        if form.is_valid():
            newform=form.save(commit=False)
            newform.user=request.user
            newform.save()
            return redirect('/')

    else:
        form = PostForm(instance=post)
    
    context = {
        'form': form ,
    }

    return render(request,'edit.html',context)

Post/templates/allposts.html
{% extends "base.html" %}
<!-- <h1>Welcome to my Blog</h1>
<a href="{% url 'blog:create_post'  %}">Add New Post</a>

{% for post in all_posts %}
    <h3> <a href=" {% url 'blog:post' post.id %}">{{ post.title}}</a> </h3>
{% endfor %} -->

{% block body %}
  
     
      <button type="button" class="btn btn-dark mr-4 float-right" ><a href="{% url 'blog:create_post' %}" style="color: white; text-decoration: none;" >Add Post</a></button>
      <div class="container">
        <div class="row mt-4">
          {% for post in all_posts %}
          <div class="col-md-4">

            <div class="card">
                {% if post.img %}
                <img src="{{ post.img.url }}" class="card-img-top" alt="...">
                {% endif %}

                <div class="card-body">
                  <h5 class="card-title">{{post.title}}</h5>
                  <p class="card-text" >{{ post.content|safe|truncatewords:10}}</p>
                  <a href="{% url 'blog:post' post.id %}" class="btn btn-primary">Know more</a>
                </div>
              </div>

           </div> 
           
          {% endfor %}
         
        </div>
      </div>

      {% endblock body %}

Post/templates/base.html
<!-- <h1>Welcome to my Blog</h1>
<a href="{% url 'blog:create_post'  %}">Add New Post</a>

{% for post in all_posts %}
    <h3> <a href=" {% url 'blog:post' post.id %}">{{ post.title}}</a> </h3>
{% endfor %} -->
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home-static\Css\style.css' %}">

    <title>Python News</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Python News</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


      </nav>
     
    
         {% block body %}
           
         {% endblock body %}
         
    
      

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

Post/templates/create.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{form}}
    <button type="submit" class="btn btn-primary">save Post</button>
</form>

Post/templates/edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}
<div style="width: 80%; margin: 5%;">
    <form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {{form.media}}    
        {% bootstrap_form form%}
    
        {%buttons%}
        <button type="submit" class="btn btn-primary">save Post</button>
        {% endbuttons%}
    
    </form>
</div>

{% endblock body %}
    

Post/templates/post.html
{% extends "base.html" %}
<!-- {{post}}<br>
{{post.content}} -->
<!-- <hr>
<a href="{% url 'blog:edit_post' post.id %}">Edit Post</a> -->

{% block body %}
<button type="button" class="btn btn-dark mr-4 float-right" ><a href="{% url 'blog:edit_post' post.id %}" style="color: white; text-decoration: none;" >update Post</a></button>


<div class="container">
  <div class="row mt-4">
      <div class="card single_post">
          <img  src="{{ post.img.url }}" class="card-img-top" alt="card img cap">
          <div class="card-body">
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">{{post.content|safe}}</p>
          </div>
     </div> 

     

  </div>
</div>

{% endblock body %}